name: Deploy to EKS

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    name: Deploy Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_CREDENTIALS_PSW }} | docker login -u ${{ secrets.DOCKERHUB_CREDENTIALS_USR }} --password-stdin

      - name: Pull Base Image from Docker Hub
        run: docker pull abodiaa/amf-base:latest

      - name: Docker Build
        run: |
          docker images -a
          docker build -t abodiaa/5g-amf:latest . 
          docker images -a

      - name: Scan Image for CVEs
        run: trivy image abodiaa/5g-amf --output trivy-report.json

      - name: Push to Docker Hub
        run: docker push abodiaa/5g-amf:latest

      - name: Build and Package Helm Chart
        run: helm package ./helm/

      - name: Configure Kubernetes Context
        run: aws eks --region us-east-1 update-kubeconfig --name 5G-Core-Net

      - name: Deploy Helm Chart on EKS
        run: helm upgrade --install amf ./helm/
